"""empty message

Revision ID: efc750404756
Revises: 9c15c934b8c3
Create Date: 2024-10-28 20:13:24.911051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc750404756'
down_revision: Union[str, None] = '9c15c934b8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collection_notes_collection_id_fkey', 'collection_notes', type_='foreignkey')
    op.create_foreign_key(None, 'collection_notes', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_collection_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_collection_id_fkey', 'products', 'collections', ['collection_id'], ['id'])
    op.drop_constraint(None, 'collection_notes', type_='foreignkey')
    op.create_foreign_key('collection_notes_collection_id_fkey', 'collection_notes', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###
