"""empty message

Revision ID: 345c2869c437
Revises: ca5640116d0f
Create Date: 2024-10-21 02:26:06.167547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345c2869c437'
down_revision: Union[str, None] = 'ca5640116d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('party_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    op.create_table('modifications_in_party',
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('modification_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modification_id'], ['modifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifications_in_party_id'), 'modifications_in_party', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modifications_in_party_id'), table_name='modifications_in_party')
    op.drop_table('modifications_in_party')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
