"""empty message

Revision ID: e1ee8bb4f67f
Revises: efc750404756
Create Date: 2024-11-12 18:38:15.893712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1ee8bb4f67f"
down_revision: Union[str, None] = "efc750404756"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM parties")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parties", sa.Column("overheads", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parties", "overheads")
    # ### end Alembic commands ###
