"""empty message

Revision ID: 347b86d8c26b
Revises: 345c2869c437
Create Date: 2024-10-22 17:05:47.728034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347b86d8c26b'
down_revision: Union[str, None] = '345c2869c437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modifications_product_id_fkey', 'modifications', type_='foreignkey')
    op.create_foreign_key(None, 'modifications', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modifications', type_='foreignkey')
    op.create_foreign_key('modifications_product_id_fkey', 'modifications', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
