"""empty message

Revision ID: 91b2d4c1afb1
Revises: e1ee8bb4f67f
Create Date: 2024-11-12 19:02:28.420144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91b2d4c1afb1"
down_revision: Union[str, None] = "e1ee8bb4f67f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM orders")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("discount", sa.Integer(), nullable=False))
    op.add_column("orders", sa.Column("promo", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "promo")
    op.drop_column("orders", "discount")
    # ### end Alembic commands ###
