"""empty message

Revision ID: 876d3cbbcdda
Revises: 4f7556f7c3e6
Create Date: 2024-10-13 23:42:54.223794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876d3cbbcdda'
down_revision: Union[str, None] = '4f7556f7c3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'size')
    # ### end Alembic commands ###
