"""empty message

Revision ID: 1afe2881e1cb
Revises: 847b5709cdfa
Create Date: 2024-09-18 15:47:56.631521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afe2881e1cb'
down_revision: Union[str, None] = '847b5709cdfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_in_order',
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_in_order_id'), 'products_in_order', ['id'], unique=False)
    op.drop_column('orders', 'summ')
    op.alter_column('products', 'measure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'remaining',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'remaining',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'measure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('orders', sa.Column('summ', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_in_order_id'), table_name='products_in_order')
    op.drop_table('products_in_order')
    # ### end Alembic commands ###
