"""empty message

Revision ID: 67d9e5ebebc0
Revises: 225f622115f6
Create Date: 2024-09-14 17:56:57.538349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d9e5ebebc0'
down_revision: Union[str, None] = '225f622115f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('remaining', sa.Integer(), nullable=True))
    op.alter_column('products', 'measure',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.execute(
        "UPDATE products SET remaining = 0"
    )
    op.execute(
        "UPDATE products SET measure = 'шт.'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'measure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'remaining')
    # ### end Alembic commands ###
