"""empty message

Revision ID: 57d2179c2db5
Revises: 876d3cbbcdda
Create Date: 2024-10-15 02:07:04.983588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57d2179c2db5"
down_revision: Union[str, None] = "876d3cbbcdda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("users", sa.Column("access_storage", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("access_crm", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("access_message", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("access_analytics", sa.Boolean(), nullable=True))

    op.execute(
        """
        UPDATE users
        SET 
            access_storage = False,
            access_crm = False,
            access_message = False,
            access_analytics = False
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "access_storage", nullable=False)
    op.alter_column("users", "access_crm", nullable=False)
    op.alter_column("users", "access_message", nullable=False)
    op.alter_column("users", "access_analytics", nullable=False)
    op.alter_column("users", "tg_username", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "tg_username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "access_analytics")
    op.drop_column("users", "access_message")
    op.drop_column("users", "access_crm")
    op.drop_column("users", "access_storage")
    # ### end Alembic commands ###
