"""empty message

Revision ID: db049efa6cb5
Revises: 
Create Date: 2024-08-14 04:47:49.045338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db049efa6cb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('messages', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('summ', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
