"""empty message

Revision ID: e97a2503ec13
Revises: 4688a4fac725
Create Date: 2024-09-11 21:02:17.421036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97a2503ec13'
down_revision: Union[str, None] = '4688a4fac725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
