"""empty message

Revision ID: 847b5709cdfa
Revises: 67d9e5ebebc0
Create Date: 2024-09-14 21:12:41.924951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847b5709cdfa'
down_revision: Union[str, None] = '67d9e5ebebc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
