"""empty message

Revision ID: 90498cedb348
Revises: b24d1f371866
Create Date: 2024-09-29 01:04:05.265805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90498cedb348'
down_revision: Union[str, None] = 'b24d1f371866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_images_product_id_fkey', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_in_order_order_id_fkey', 'products_in_order', type_='foreignkey')
    op.drop_constraint('products_in_order_product_id_fkey', 'products_in_order', type_='foreignkey')
    op.create_foreign_key(None, 'products_in_order', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products_in_order', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_in_order', type_='foreignkey')
    op.drop_constraint(None, 'products_in_order', type_='foreignkey')
    op.create_foreign_key('products_in_order_product_id_fkey', 'products_in_order', 'products', ['product_id'], ['id'])
    op.create_foreign_key('products_in_order_order_id_fkey', 'products_in_order', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('product_images_product_id_fkey', 'product_images', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
