"""empty message

Revision ID: b17cf96e4f27
Revises: 31dbb64a7183
Create Date: 2025-02-06 06:12:04.898083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b17cf96e4f27'
down_revision: Union[str, None] = '31dbb64a7183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_auto_reply',
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('buttons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_auto_reply_id'), 'channel_auto_reply', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_auto_reply_id'), table_name='channel_auto_reply')
    op.drop_table('channel_auto_reply')
    # ### end Alembic commands ###
