"""empty message

Revision ID: 3135bfe1187f
Revises: b17cf96e4f27
Create Date: 2025-02-20 21:58:29.183416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3135bfe1187f'
down_revision: Union[str, None] = 'b17cf96e4f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_auto_reply', sa.Column('photo_file_id', sa.String(), nullable=True))
    op.drop_column('channel_auto_reply', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_auto_reply', sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('channel_auto_reply', 'photo_file_id')
    # ### end Alembic commands ###
